# Generated by Django 5.2 on 2025-04-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrostore', '0003_categoria_producto_descripcion_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
